### ISSUE TITLE
Database config issues

### ISSUE THREAD

**Issue by Dobbelsteen** [iRail/gtfs-tdt#26]
"/vagrant/datasources/DeLijn/init.sh": Following line of code

>  --local-infile -u root < /vagrant/datasources/delijn/importDeLijn.sql

should be

>  --local-infile -u root -proot < /vagrant/datasources/delijn/importDeLijn.sql

This also occurs in the other init.sh files (mivb, tec)

Installed resources are missing the root password, see:

> "\gtfs-tdt\tdt\installed\DeLijnResource\Config.class.php"

**Comment by brechtvdv** [comment]
I know, haven't pushed those changes yet :)
