### ISSUE TITLE
csv parse error

### ISSUE THREAD

**Issue by brechtvdv** [iRail/gtfs-tdt#32]
Error for columns that are enclosed in "..." and contain a comma

TEC:LPLc65-2,,"PLAINEVAUX route du Condroz, 65",50.549121,5.504338,0,stoparea:TEC:LPLc65-,,1,,

**Comment by pietercolpaert** [comment]
https://github.com/iRail/gtfs-tdt/blob/master/datasources/tec/importTec.sql#L177
→ make sure it has enclosed by instead:
https://dev.mysql.com/doc/refman/5.1/en/load-data.html
