### ISSUE TITLE
All queries return empty result

### ISSUE THREAD

**Issue by verydeep123** [iRail/gtfs-tdt#33]
Hello,

For the last few days, the queries do not return any data at all:

Ex:
https://data.irail.be/DeLijn/Departures/88498/2015/09/12/14/41.json

This is the response:
{"Departures":[]}

Is there any change in API?

**Comment by Tuinslak** [comment]
Seems the zip file we receive is empty. Investigating.

**Comment by Tuinslak** [comment]
Redownloaded & imported file, solved. 

GTFS also located here: http://gtfs.irail.be/de-lijn/
